# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bce973be6167f57a2a811422fe498f5ed27adbb21be80ee2926c1478b01f4540e00f80e864eeb654dff44f978ba194e623dabef6044e79df6a84ff1d211d2a78

test:
  secret_key_base: 5d83f843cc47d03bb19a64266655f32c90ccc729167725efac4999373d54066b194c0555ed184d5fc6d0a04073c93dee4742136f053917cdb145bcf68cd81af6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
